# build environment
FROM node:alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package*.json ./
RUN npm ci
RUN npm install react-scripts
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=0 /app/build /usr/share/nginx/html
#COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]