version: "3.7"

services:
  db:
    container_name: db
    image: pgrouting/pgrouting:12-3.0-2.6.3
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: api
    build: ./api-service/
    volumes:
      - ./api-service/:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      DB_PATH: "postgresql://postgres:postgres@pgsql-server:5432/fullstackdb"
      FLASK_DEBUG: 1
    links:
      - "db:pgsql-server"

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db-data:
  pgadmin-data:
